# shellcheck shell=bash disable=SC2034 # State variables are read by the sourcing script.
# Lifecycle helpers for the local SeaweedFS S3 service (tests/e2e/local_s3.sh)
# used by the hosted provisioning scripts.
#
# local_s3_start RUNTIME LOG  start the wrapper in the background, wait for
#                             readiness and export TEST_S3_ENDPOINT/TEST_S3_BUCKET.
# local_s3_stop RUNTIME       stop the wrapper; fail if it died early or left
#                             its owned weed process behind.
# local_s3_budget_ok RUNTIME  fail (printing the report) if the disk budget
#                             monitor stopped the service.
#
# State: LOCAL_S3_PID (wrapper), LOCAL_S3_WEED_PID (weed server) and
# LOCAL_S3_STOPPED (true once no owned process remains).

LOCAL_S3_READY_TIMEOUT_SEC=120
LOCAL_S3_PID=""
LOCAL_S3_WEED_PID=""
LOCAL_S3_STOPPED=true

local_s3_start() {
    local runtime="$1" log="$2" attempt
    bash tests/e2e/local_s3.sh "$runtime" > "$log" 2>&1 &
    LOCAL_S3_PID=$!
    LOCAL_S3_STOPPED=false
    for ((attempt = 0; attempt < LOCAL_S3_READY_TIMEOUT_SEC; attempt++)); do
        if ! kill -0 "$LOCAL_S3_PID" 2>/dev/null; then
            cat "$log" >&2
            echo "local S3 wrapper exited before readiness" >&2
            return 1
        fi
        if grep -q '^ready endpoint=' "$log"; then
            LOCAL_S3_WEED_PID="$(cat "$runtime/weed.pid")"
            [[ "$LOCAL_S3_WEED_PID" =~ ^[1-9][0-9]*$ ]] || {
                echo "local S3 wrote an invalid weed.pid" >&2
                return 1
            }
            # shellcheck source=/dev/null # Generated by local_s3.sh.
            source "$runtime/local_s3.env"
            export TEST_S3_ENDPOINT="$LOCAL_S3_ENDPOINT"
            export TEST_S3_BUCKET="$LOCAL_S3_BUCKET"
            return 0
        fi
        sleep 1
    done
    echo "local S3 readiness timed out" >&2
    return 1
}

local_s3_stop() {
    local runtime="$1" status=0
    [[ -n "$LOCAL_S3_PID" ]] || return 0
    if kill -0 "$LOCAL_S3_PID" 2>/dev/null; then
        kill -TERM "$LOCAL_S3_PID" || status=1
        wait "$LOCAL_S3_PID" || true
    else
        echo "local S3 wrapper exited unexpectedly" >&2
        wait "$LOCAL_S3_PID" || true
        status=1
    fi
    if [[ -f "$runtime/weed.pid" ]] ||
       { [[ -n "$LOCAL_S3_WEED_PID" ]] && kill -0 "$LOCAL_S3_WEED_PID" 2>/dev/null; }; then
        echo "local S3 cleanup did not stop its owned service; retaining runtime" >&2
        return 1
    fi
    LOCAL_S3_STOPPED=true
    return "$status"
}

local_s3_budget_ok() {
    local report="$1/disk-budget-failure.txt"
    [[ -f "$report" ]] || return 0
    cat "$report" >&2
    return 1
}
