"""Cross-check the pinned Rust/Tink Streaming AEAD vectors with Tink Python.

Requires the official ``tink`` Python package. The pinned runtime vector is
generated by this same primitive with the test key and associated data.
"""

import io
import sys
from pathlib import Path

import tink.streaming_aead as streaming_aead
from tink import core
from tink.proto import aes_gcm_hkdf_streaming_pb2, common_pb2, tink_pb2
from tink.streaming_aead import _raw_streaming_aead


FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"
AAD = b"tink cross-language vector"
PLAINTEXT = b"Tink-compatible reference payload"
KEY = bytes(range(32))


class RetainedBytesIO(io.BytesIO):
    def close(self):
        self.value_after_close = self.getvalue()
        super().close()


def primitive():
    streaming_aead.register()
    key = aes_gcm_hkdf_streaming_pb2.AesGcmHkdfStreamingKey(
        version=0, key_value=KEY
    )
    key.params.hkdf_hash_type = common_pb2.SHA256
    key.params.derived_key_size = 16
    key.params.ciphertext_segment_size = 1_048_576
    key_data = tink_pb2.KeyData(
        type_url="type.googleapis.com/google.crypto.tink.AesGcmHkdfStreamingKey",
        value=key.SerializeToString(),
        key_material_type=tink_pb2.KeyData.SYMMETRIC,
    )
    return core.Registry.primitive(key_data, _raw_streaming_aead.RawStreamingAead)


def decrypt_with_tink(tink_primitive, fixture: str) -> None:
    ciphertext = bytes.fromhex((FIXTURES / fixture).read_text(encoding="ascii").strip())
    with tink_primitive.new_raw_decrypting_stream(
        io.BytesIO(ciphertext), AAD, close_ciphertext_source=False
    ) as plaintext:
        assert plaintext.read() == PLAINTEXT


def main() -> None:
    tink_primitive = primitive()
    if sys.argv[1:] == ["--round-trip"]:
        ciphertext = sys.stdin.buffer.read()
        expected = bytes(index % 251 for index in range(3 * 1024 * 1024 + 17))
        with tink_primitive.new_raw_decrypting_stream(
            io.BytesIO(ciphertext), AAD, close_ciphertext_source=False
        ) as plaintext:
            decrypted = plaintext.read()
        assert decrypted == expected, "Rust ciphertext did not decrypt to the expected payload"
        ciphertext = RetainedBytesIO()
        with tink_primitive.new_raw_encrypting_stream(ciphertext, AAD) as encryptor:
            encryptor.write(decrypted)
        sys.stdout.buffer.write(ciphertext.value_after_close)
        return
    if sys.argv[1:]:
        raise ValueError("expected no arguments or --round-trip")
    decrypt_with_tink(tink_primitive, "tink_vector.hex")
    decrypt_with_tink(tink_primitive, "tink_runtime_vector.hex")

    ciphertext = RetainedBytesIO()
    with tink_primitive.new_raw_encrypting_stream(ciphertext, AAD) as encryptor:
        encryptor.write(PLAINTEXT)
    generated = ciphertext.value_after_close
    with tink_primitive.new_raw_decrypting_stream(
        io.BytesIO(generated), AAD, close_ciphertext_source=False
    ) as plaintext:
        assert plaintext.read() == PLAINTEXT
    assert len(generated) == 73


if __name__ == "__main__":
    main()
